import cgi

data = cgi.FieldStorage()
id = data.getvalue("id")

error = "Username or password wrong"

if id == "jhu8lH79Gf":

    print("Content-Type: text/html")
    print()
    print("<!DOCTYPE html>")
    print("<html lang='en'>")
    print("<head>")
    print("<!-- META -->")
    print("<meta charset='UTF-8'>")
    print("<!-- TITLE -->")
    print("<title>Kristaberslo | Home</title>")
    print("<!-- CSS by Bootstrap -->")
    print("<link href='/assets/css/bootstrap.min.css' rel='stylesheet'>")
    print("<!-- JS by Bootstrap -->")
    print("<script src='/assets/js/bootstrap.min.js'></script>")
    print("</head>")
    print("<body>")
    print("<div class='container'>")
    print("<br>")
    print("<h1 align='center'>Welcome to Kristaberslo</h1>")
    print("<hr>")
    print("<div class='row'>")
    print("<div class='col-sm'>")
    print("<a href='/'>Home</a>")
    print("</div>")
    print("<div class='col-sm'>")
    print("<a href='/?logout'>Log Out</a>")
    print("</div>")
    print("</div>")
    print("<hr>")
    print("<div class='row' align='center'>")
    print("<div class='col-sm'>")
    print("<h1></h1>")
    print("<a href='' class='btn btn-lg btn-success'><i class='fa fa-plus' aria-hidden='true'></i> Add a product</a>")
    print("</div>")
    print("<div class='col-sm'>")
    print("<h1></h1>")
    print("<a href='' class='btn btn-lg btn-success'><i class='fa fa-minus' aria-hidden='true'></i> Remove a product</a>")
    print("</div>")
    print("</div>")
    print("<hr>")
    print("<p class='muted'>Copyright &copy; 2021 Kristaberslo AS. <a href='/admin.html'>Admin Login</a></p>")
    print("</div>")
    print("</body>")
    print("</html>")

else:
    print("Content-Type: text/html")
    print()
    print("<!DOCTYPE html>")
    print("<html lang='en'>")
    print("<h1 align='center'>You are not allowed to view this page</h1>")
